FROM registry.cn-shanghai.aliyuncs.com/lebai/util:14.04

WORKDIR /app
COPY . .
RUN ls -la
COPY ./.git /app/.git

ARG AWS_ENDPOINT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_ENDPOINT=${AWS_ENDPOINT}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

RUN bash ./ci.sh
